services:
  php80:
    container_name: php-opentsdb-client-lib-php-80
    image: php-opentsdb-client-lib-80
    build:
      context: ./
      dockerfile: ./.docker/php80/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - php-opentsdb-client-lib

  php81:
    container_name: php-opentsdb-client-lib-php-81
    image: php-opentsdb-client-lib-81
    build:
      context: ./
      dockerfile: ./.docker/php81/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - php-opentsdb-client-lib

  php82:
    container_name: php-opentsdb-client-lib-php-82
    image: php-opentsdb-client-lib-82
    build:
      context: ./
      dockerfile: ./.docker/php82/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - php-opentsdb-client-lib

  php83:
    container_name: php-opentsdb-client-lib-php-83
    image: php-opentsdb-client-lib-83
    build:
      context: ./
      dockerfile: ./.docker/php83/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - php-opentsdb-client-lib

  opentsdb:
    container_name: php-opentsdb-client-lib-opentsdb
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30 # Give time for hbase to shut down, otherwise data corruption may result
    ports:
      - 4242:4242
    networks:
      - php-opentsdb-client-lib
    volumes:
      - "./.docker_data_hbase:/data/hbase"

networks:
  php-opentsdb-client-lib:
    driver: bridge
