services:
  php80:
    container_name: php-opentsdb-client-lib-80
    image: php-opentsdb-client-lib-80
    build:
      context: ./
      dockerfile: ./.docker/php80/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php81:
    container_name: php-opentsdb-client-lib-81
    image: php-opentsdb-client-lib-81
    build:
      context: ./
      dockerfile: ./.docker/php81/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php82:
    container_name: php-opentsdb-client-lib-82
    image: php-opentsdb-client-lib-82
    build:
      context: ./
      dockerfile: ./.docker/php82/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php83:
    container_name: php-opentsdb-client-lib-83
    image: php-opentsdb-client-lib-83
    build:
      context: ./
      dockerfile: ./.docker/php83/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
